"""add files notifications driver_push_tokens driver_location_pings

Revision ID: 305cb592a393
Revises: 9f8e0b29cc6c
Create Date: 2026-04-25 21:32:37.783372

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305cb592a393'
down_revision: Union[str, None] = '9f8e0b29cc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_is_deleted'), 'files', ['is_deleted'], unique=False)
    op.create_index('ix_files_tenant_attach', 'files', ['tenant_id', 'domain', 'object_id'], unique=False)
    op.create_index(op.f('ix_files_tenant_id'), 'files', ['tenant_id'], unique=False)
    op.create_index('ix_files_tenant_kind', 'files', ['tenant_id', 'kind'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'PUSH', 'WEBHOOK', name='notification_channel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'DELIVERED', name='notification_status'), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_tenant_status', 'notifications', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_notif_tenant_user_read', 'notifications', ['tenant_id', 'user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_table('driver_location_pings',
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('heading_deg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('accuracy_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dlp_tenant_driver_time', 'driver_location_pings', ['tenant_id', 'driver_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_driver_location_pings_is_deleted'), 'driver_location_pings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_driver_location_pings_tenant_id'), 'driver_location_pings', ['tenant_id'], unique=False)
    op.create_table('driver_push_tokens',
    sa.Column('driver_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_dpt_token')
    )
    op.create_index('ix_dpt_tenant_driver_platform', 'driver_push_tokens', ['tenant_id', 'driver_id', 'platform'], unique=False)
    op.create_index(op.f('ix_driver_push_tokens_is_deleted'), 'driver_push_tokens', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_driver_push_tokens_tenant_id'), 'driver_push_tokens', ['tenant_id'], unique=False)
    op.create_foreign_key('fk_legs_settlement', 'legs', 'settlements', ['settlement_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_settlements_leg', 'settlements', 'legs', ['leg_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_settlements_leg', 'settlements', type_='foreignkey')
    op.drop_constraint('fk_legs_settlement', 'legs', type_='foreignkey')
    op.drop_index(op.f('ix_driver_push_tokens_tenant_id'), table_name='driver_push_tokens')
    op.drop_index(op.f('ix_driver_push_tokens_is_deleted'), table_name='driver_push_tokens')
    op.drop_index('ix_dpt_tenant_driver_platform', table_name='driver_push_tokens')
    op.drop_table('driver_push_tokens')
    op.drop_index(op.f('ix_driver_location_pings_tenant_id'), table_name='driver_location_pings')
    op.drop_index(op.f('ix_driver_location_pings_is_deleted'), table_name='driver_location_pings')
    op.drop_index('ix_dlp_tenant_driver_time', table_name='driver_location_pings')
    op.drop_table('driver_location_pings')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index('ix_notif_tenant_user_read', table_name='notifications')
    op.drop_index('ix_notif_tenant_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_files_tenant_kind', table_name='files')
    op.drop_index(op.f('ix_files_tenant_id'), table_name='files')
    op.drop_index('ix_files_tenant_attach', table_name='files')
    op.drop_index(op.f('ix_files_is_deleted'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
