"""init schema with 14 tables

Revision ID: 9f8e0b29cc6c
Revises: 
Create Date: 2026-04-25 21:13:08.821280

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8e0b29cc6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('plan_tier', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_tenants_slug')
    )
    op.create_index(op.f('ix_tenants_is_deleted'), 'tenants', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.create_table('customers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('billing_address', sa.String(length=500), nullable=True),
    sa.Column('contact_name', sa.String(length=128), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_customers_tenant_code')
    )
    op.create_index(op.f('ix_customers_is_deleted'), 'customers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_index('ix_customers_tenant_name', 'customers', ['tenant_id', 'name'], unique=False)
    op.create_table('rate_settings',
    sa.Column('rate_type', sa.Enum('FLAT_RATE', 'PERCENTAGE', 'PER_MILE', name='rate_type'), nullable=False),
    sa.Column('flat_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate_percent', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('rate_per_mile', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_settings_is_deleted'), 'rate_settings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rate_settings_tenant_id'), 'rate_settings', ['tenant_id'], unique=False)
    op.create_index('ix_rate_tenant_active_effective', 'rate_settings', ['tenant_id', 'is_active', 'effective_date'], unique=False)
    op.create_table('terminals',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_terminals_tenant_code')
    )
    op.create_index(op.f('ix_terminals_is_deleted'), 'terminals', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_terminals_tenant_id'), 'terminals', ['tenant_id'], unique=False)
    op.create_index('ix_terminals_tenant_name', 'terminals', ['tenant_id', 'name'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'DISPATCHER', 'DRIVER', name='user_role'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_role', 'users', ['tenant_id', 'role'], unique=False)
    op.create_table('vessels',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('imo_number', sa.String(length=16), nullable=True),
    sa.Column('line', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_vessels_tenant_name')
    )
    op.create_index(op.f('ix_vessels_is_deleted'), 'vessels', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_vessels_tenant_id'), 'vessels', ['tenant_id'], unique=False)
    op.create_index('ix_vessels_tenant_imo', 'vessels', ['tenant_id', 'imo_number'], unique=False)
    op.create_table('drivers',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('license_state', sa.String(length=8), nullable=True),
    sa.Column('truck_number', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_drivers_user')
    )
    op.create_index(op.f('ix_drivers_is_deleted'), 'drivers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_drivers_tenant_id'), 'drivers', ['tenant_id'], unique=False)
    op.create_index('ix_drivers_tenant_status', 'drivers', ['tenant_id', 'is_active'], unique=False)
    op.create_table('locations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('YARD', 'CUSTOMER', 'PORT', 'OTHER', name='location_kind'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_is_deleted'), 'locations', ['is_deleted'], unique=False)
    op.create_index('ix_locations_tenant_customer', 'locations', ['tenant_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_locations_tenant_id'), 'locations', ['tenant_id'], unique=False)
    op.create_index('ix_locations_tenant_kind', 'locations', ['tenant_id', 'kind'], unique=False)
    op.create_table('settlements',
    sa.Column('leg_id', sa.String(length=36), nullable=False),
    sa.Column('system_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('driver_reported_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discrepancy', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('has_flag', sa.Boolean(), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('settlement_status', sa.Enum('PENDING', 'CALCULATED', 'ADJUSTED', 'APPROVED', name='settlement_status'), nullable=False),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('unapproved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unapproved_by', sa.String(length=36), nullable=True),
    sa.Column('unapproved_reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['leg_id'], ['legs.id'], name='fk_settlements_leg', ondelete='CASCADE', use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unapproved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leg_id', name='uq_settlements_leg')
    )
    op.create_index(op.f('ix_settlements_is_deleted'), 'settlements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_settlements_tenant_id'), 'settlements', ['tenant_id'], unique=False)
    op.create_index('ix_settlements_tenant_settled', 'settlements', ['tenant_id', 'is_settled'], unique=False)
    op.create_index('ix_settlements_tenant_status', 'settlements', ['tenant_id', 'settlement_status'], unique=False)
    op.create_table('delivery_orders',
    sa.Column('status', sa.Enum('PLANNING', 'DISPATCHED', 'YARD_STAGED', 'FINAL_DELIVERY', 'EMPTY_STAGED', 'COMPLETED', name='delivery_status'), nullable=False),
    sa.Column('direction', sa.Enum('IMPORT', 'EXPORT', name='shipment_direction'), nullable=False),
    sa.Column('bl_number', sa.String(length=64), nullable=True),
    sa.Column('booking_number', sa.String(length=64), nullable=True),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('terminal_id', sa.String(length=36), nullable=True),
    sa.Column('vessel_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_location_id', sa.String(length=36), nullable=True),
    sa.Column('return_location_id', sa.String(length=36), nullable=True),
    sa.Column('container_number', sa.String(length=16), nullable=True),
    sa.Column('container_size', sa.Enum('SIZE_20GP', 'SIZE_40GP', 'SIZE_40HC', 'SIZE_40OT', 'SIZE_45HC', 'SIZE_20RF', 'SIZE_40RF', name='container_size'), nullable=True),
    sa.Column('container_type', sa.String(length=32), nullable=True),
    sa.Column('chassis_number', sa.String(length=32), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_appointment', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_appointment', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_appointment', sa.DateTime(timezone=True), nullable=True),
    sa.Column('demurrage_lfd', sa.Date(), nullable=True),
    sa.Column('detention_lfd', sa.Date(), nullable=True),
    sa.Column('empty_date', sa.Date(), nullable=True),
    sa.Column('loaded_date', sa.Date(), nullable=True),
    sa.Column('bl_released', sa.Boolean(), nullable=False),
    sa.Column('pier_pass_paid', sa.Boolean(), nullable=False),
    sa.Column('customs_cleared', sa.Boolean(), nullable=False),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['return_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_orders_is_deleted'), 'delivery_orders', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_delivery_orders_tenant_id'), 'delivery_orders', ['tenant_id'], unique=False)
    op.create_index('ix_do_tenant_container', 'delivery_orders', ['tenant_id', 'container_number'], unique=False)
    op.create_index('ix_do_tenant_created', 'delivery_orders', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_do_tenant_customer', 'delivery_orders', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_do_tenant_status', 'delivery_orders', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_do_tenant_terminal', 'delivery_orders', ['tenant_id', 'terminal_id'], unique=False)
    op.create_table('extra_charges',
    sa.Column('settlement_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extra_charges_is_deleted'), 'extra_charges', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_extra_charges_tenant_id'), 'extra_charges', ['tenant_id'], unique=False)
    op.create_index('ix_extra_tenant_settlement', 'extra_charges', ['tenant_id', 'settlement_id'], unique=False)
    op.create_table('settlement_audit_logs',
    sa.Column('settlement_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sal_tenant_settlement', 'settlement_audit_logs', ['tenant_id', 'settlement_id'], unique=False)
    op.create_index(op.f('ix_settlement_audit_logs_is_deleted'), 'settlement_audit_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_settlement_audit_logs_tenant_id'), 'settlement_audit_logs', ['tenant_id'], unique=False)
    op.create_table('legs',
    sa.Column('delivery_order_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.Enum('PLANNING', 'DISPATCHED', 'YARD_STAGED', 'FINAL_DELIVERY', 'EMPTY_STAGED', 'COMPLETED', name='delivery_status'), nullable=False),
    sa.Column('move_type', sa.Enum('LOADED', 'EMPTY', name='move_type'), nullable=False),
    sa.Column('service_type', sa.Enum('LIVE', 'DROP', name='service_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'COMPLETED', 'FAILED', name='leg_status'), nullable=False),
    sa.Column('driver_id', sa.String(length=36), nullable=True),
    sa.Column('pickup_location_id', sa.String(length=36), nullable=True),
    sa.Column('pickup_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_location_id', sa.String(length=36), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('storage_days', sa.Integer(), nullable=False),
    sa.Column('yard_in_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('yard_out_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('settlement_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_order_id'], ['delivery_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name='fk_legs_settlement', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legs_is_deleted'), 'legs', ['is_deleted'], unique=False)
    op.create_index('ix_legs_tenant_do', 'legs', ['tenant_id', 'delivery_order_id'], unique=False)
    op.create_index('ix_legs_tenant_driver_status', 'legs', ['tenant_id', 'driver_id', 'status'], unique=False)
    op.create_index(op.f('ix_legs_tenant_id'), 'legs', ['tenant_id'], unique=False)
    op.create_index('ix_legs_tenant_status', 'legs', ['tenant_id', 'status'], unique=False)
    op.create_table('street_turns',
    sa.Column('import_order_id', sa.String(length=36), nullable=False),
    sa.Column('export_order_id', sa.String(length=36), nullable=False),
    sa.Column('container_number', sa.String(length=16), nullable=False),
    sa.Column('link_type', sa.Enum('AUTO', 'MANUAL', name='street_turn_link_type'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['export_order_id'], ['delivery_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_order_id'], ['delivery_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('export_order_id', name='uq_st_export'),
    sa.UniqueConstraint('import_order_id', name='uq_st_import')
    )
    op.create_index('ix_st_tenant_container', 'street_turns', ['tenant_id', 'container_number'], unique=False)
    op.create_index(op.f('ix_street_turns_is_deleted'), 'street_turns', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_street_turns_tenant_id'), 'street_turns', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_street_turns_tenant_id'), table_name='street_turns')
    op.drop_index(op.f('ix_street_turns_is_deleted'), table_name='street_turns')
    op.drop_index('ix_st_tenant_container', table_name='street_turns')
    op.drop_table('street_turns')
    op.drop_index('ix_legs_tenant_status', table_name='legs')
    op.drop_index(op.f('ix_legs_tenant_id'), table_name='legs')
    op.drop_index('ix_legs_tenant_driver_status', table_name='legs')
    op.drop_index('ix_legs_tenant_do', table_name='legs')
    op.drop_index(op.f('ix_legs_is_deleted'), table_name='legs')
    op.drop_table('legs')
    op.drop_index(op.f('ix_settlement_audit_logs_tenant_id'), table_name='settlement_audit_logs')
    op.drop_index(op.f('ix_settlement_audit_logs_is_deleted'), table_name='settlement_audit_logs')
    op.drop_index('ix_sal_tenant_settlement', table_name='settlement_audit_logs')
    op.drop_table('settlement_audit_logs')
    op.drop_index('ix_extra_tenant_settlement', table_name='extra_charges')
    op.drop_index(op.f('ix_extra_charges_tenant_id'), table_name='extra_charges')
    op.drop_index(op.f('ix_extra_charges_is_deleted'), table_name='extra_charges')
    op.drop_table('extra_charges')
    op.drop_index('ix_do_tenant_terminal', table_name='delivery_orders')
    op.drop_index('ix_do_tenant_status', table_name='delivery_orders')
    op.drop_index('ix_do_tenant_customer', table_name='delivery_orders')
    op.drop_index('ix_do_tenant_created', table_name='delivery_orders')
    op.drop_index('ix_do_tenant_container', table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_tenant_id'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_is_deleted'), table_name='delivery_orders')
    op.drop_table('delivery_orders')
    op.drop_index('ix_settlements_tenant_status', table_name='settlements')
    op.drop_index('ix_settlements_tenant_settled', table_name='settlements')
    op.drop_index(op.f('ix_settlements_tenant_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_is_deleted'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index('ix_locations_tenant_kind', table_name='locations')
    op.drop_index(op.f('ix_locations_tenant_id'), table_name='locations')
    op.drop_index('ix_locations_tenant_customer', table_name='locations')
    op.drop_index(op.f('ix_locations_is_deleted'), table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_drivers_tenant_status', table_name='drivers')
    op.drop_index(op.f('ix_drivers_tenant_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_is_deleted'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index('ix_vessels_tenant_imo', table_name='vessels')
    op.drop_index(op.f('ix_vessels_tenant_id'), table_name='vessels')
    op.drop_index(op.f('ix_vessels_is_deleted'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index('ix_users_tenant_role', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_terminals_tenant_name', table_name='terminals')
    op.drop_index(op.f('ix_terminals_tenant_id'), table_name='terminals')
    op.drop_index(op.f('ix_terminals_is_deleted'), table_name='terminals')
    op.drop_table('terminals')
    op.drop_index('ix_rate_tenant_active_effective', table_name='rate_settings')
    op.drop_index(op.f('ix_rate_settings_tenant_id'), table_name='rate_settings')
    op.drop_index(op.f('ix_rate_settings_is_deleted'), table_name='rate_settings')
    op.drop_table('rate_settings')
    op.drop_index('ix_customers_tenant_name', table_name='customers')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_deleted'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_is_deleted'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
