"""phase_d_notification

Revision ID: 22544080dbc1
Revises: 66e45de2765c
Create Date: 2026-04-26 11:23:11.113167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22544080dbc1'
down_revision: Union[str, None] = '66e45de2765c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('PUSH', 'EMAIL', 'SMS', 'WEBHOOK', name='notification_channel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'DELIVERED', name='notification_status'), server_default='PENDING', nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_notification_tenant_id_id')
    )
    op.create_index('ix_notification_tenant_active_id', 'notification', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_notification_tenant_created_at', 'notification', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_tenant_id'), 'notification', ['tenant_id'], unique=False)
    op.create_index('ix_notification_tenant_status', 'notification', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_notification_tenant_user_read', 'notification', ['tenant_id', 'user_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_tenant_user_read', table_name='notification')
    op.drop_index('ix_notification_tenant_status', table_name='notification')
    op.drop_index(op.f('ix_notification_tenant_id'), table_name='notification')
    op.drop_index('ix_notification_tenant_created_at', table_name='notification')
    op.drop_index('ix_notification_tenant_active_id', table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
