"""add dual_transaction

Revision ID: 3442834d82d5
Revises: e863e0648d25
Create Date: 2026-06-09 18:59:35.725941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3442834d82d5'
down_revision: Union[str, None] = 'e863e0648d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dual_transaction',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('return_leg_id', sa.Integer(), nullable=False),
    sa.Column('pickup_leg_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'COMPLETED', 'CANCELLED', name='dual_transaction_status'), server_default='PLANNED', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pickup_leg_id'], ['leg.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['return_leg_id'], ['leg.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['truck_id'], ['truck.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'id', name='uq_dual_transaction_team_id_id')
    )
    op.create_index('ix_dual_transaction_team_active_id', 'dual_transaction', ['team_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_dual_transaction_team_driver', 'dual_transaction', ['team_id', 'driver_id'], unique=False)
    op.create_index(op.f('ix_dual_transaction_team_id'), 'dual_transaction', ['team_id'], unique=False)
    op.create_index('ix_dual_transaction_team_pickup_leg', 'dual_transaction', ['team_id', 'pickup_leg_id'], unique=False)
    op.create_index('ix_dual_transaction_team_return_leg', 'dual_transaction', ['team_id', 'return_leg_id'], unique=False)
    op.create_index('ix_dual_transaction_team_status', 'dual_transaction', ['team_id', 'status'], unique=False)
    op.create_index('ix_dual_transaction_team_updated_at', 'dual_transaction', ['team_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dual_transaction_team_updated_at', table_name='dual_transaction')
    op.drop_index('ix_dual_transaction_team_status', table_name='dual_transaction')
    op.drop_index('ix_dual_transaction_team_return_leg', table_name='dual_transaction')
    op.drop_index('ix_dual_transaction_team_pickup_leg', table_name='dual_transaction')
    op.drop_index(op.f('ix_dual_transaction_team_id'), table_name='dual_transaction')
    op.drop_index('ix_dual_transaction_team_driver', table_name='dual_transaction')
    op.drop_index('ix_dual_transaction_team_active_id', table_name='dual_transaction')
    op.drop_table('dual_transaction')
    # ### end Alembic commands ###
