"""phase_f_location_ping_push_token

Revision ID: 3c1dbafe24d0
Revises: 22544080dbc1
Create Date: 2026-04-26 13:59:50.258742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1dbafe24d0'
down_revision: Union[str, None] = '22544080dbc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_ping',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('heading_deg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('accuracy_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_location_ping_tenant_id_id')
    )
    op.create_index('ix_location_ping_tenant_active_id', 'location_ping', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_location_ping_tenant_driver_time', 'location_ping', ['tenant_id', 'driver_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_location_ping_tenant_id'), 'location_ping', ['tenant_id'], unique=False)
    op.create_table('push_token',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'platform', 'token', name='uq_push_token_driver_platform_token'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_push_token_tenant_id_id')
    )
    op.create_index('ix_push_token_tenant_active_id', 'push_token', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_push_token_tenant_driver', 'push_token', ['tenant_id', 'driver_id'], unique=False)
    op.create_index(op.f('ix_push_token_tenant_id'), 'push_token', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_token_tenant_id'), table_name='push_token')
    op.drop_index('ix_push_token_tenant_driver', table_name='push_token')
    op.drop_index('ix_push_token_tenant_active_id', table_name='push_token')
    op.drop_table('push_token')
    op.drop_index(op.f('ix_location_ping_tenant_id'), table_name='location_ping')
    op.drop_index('ix_location_ping_tenant_driver_time', table_name='location_ping')
    op.drop_index('ix_location_ping_tenant_active_id', table_name='location_ping')
    op.drop_table('location_ping')
    # ### end Alembic commands ###
