"""leg redesign columns and status

Revision ID: 475da54ea830
Revises: db7a5c780ae8
Create Date: 2026-06-09 17:20:18.126358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '475da54ea830'
down_revision: Union[str, None] = 'db7a5c780ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leg', sa.Column('from_location_type', sa.Enum('TERMINAL', 'YARD', 'CUSTOMER', name='leg_from_location_type'), nullable=True))
    op.add_column('leg', sa.Column('to_location_type', sa.Enum('TERMINAL', 'YARD', 'CUSTOMER', name='leg_to_location_type'), nullable=True))
    op.add_column('leg', sa.Column('move_code', sa.Enum('PPU', 'PRE', 'PPL', 'DRP', 'STR', 'TRL', 'RMP', 'OTR', 'ERP', name='leg_move_code'), nullable=True))
    op.add_column('leg', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    # ── 기존 enum 확장 (autogenerate 가 MySQL ENUM 변경을 감지 못해 수동) ──
    op.alter_column('leg', 'status',
        existing_type=mysql.ENUM('PENDING', 'IN_TRANSIT', 'COMPLETED', 'FAILED', 'DRY_RUN'),
        type_=mysql.ENUM('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'COMPLETED', 'FAILED', 'DRY_RUN'),
        existing_nullable=False)
    op.alter_column('leg', 'service_type',
        existing_type=mysql.ENUM('LIVE', 'DROP'),
        type_=mysql.ENUM('LIVE', 'DROP', 'NONE'),
        existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leg', 'service_type',
        existing_type=mysql.ENUM('LIVE', 'DROP', 'NONE'),
        type_=mysql.ENUM('LIVE', 'DROP'),
        existing_nullable=False)
    op.alter_column('leg', 'status',
        existing_type=mysql.ENUM('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'COMPLETED', 'FAILED', 'DRY_RUN'),
        type_=mysql.ENUM('PENDING', 'IN_TRANSIT', 'COMPLETED', 'FAILED', 'DRY_RUN'),
        existing_nullable=False)
    op.drop_column('leg', 'assigned_at')
    op.drop_column('leg', 'move_code')
    op.drop_column('leg', 'to_location_type')
    op.drop_column('leg', 'from_location_type')
    # ### end Alembic commands ###
