"""initial

Revision ID: 4cbe21b2c5c9
Revises: 
Create Date: 2026-04-05 17:53:41.730187
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4cbe21b2c5c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), server_default='email', nullable=False),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='rolesenum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('event_notification_enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('language', sa.String(length=10), server_default='auto', nullable=True),
    sa.Column('is_active_true', sa.Integer(), sa.Computed('CASE WHEN is_active = 1 THEN 1 ELSE NULL END', persisted=False), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_auth_provider', 'user', ['auth_provider'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_index('uq_user_email_active_true', 'user', ['email', 'is_active_true'], unique=True)
    op.create_index('uq_user_oauth_active', 'user', ['auth_provider', 'oauth_id', 'is_active_true'], unique=True)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permissions_category', 'permissions', ['category'], unique=False)
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('teams',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_by', sa.Integer(), nullable=True),
    sa.Column('purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_locked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('memo', sa.String(length=3000), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='Asia/Seoul', nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_purge_at'), 'teams', ['purge_at'], unique=False)
    op.create_table('file_asset',
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.Enum('USER', 'TEAM', name='file_domain'), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('subdir', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('logical_path', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'id', name='uq_file_asset_team_id_id')
    )
    op.create_index('ix_file_asset_domain_obj', 'file_asset', ['domain', 'object_id'], unique=False)
    op.create_index(op.f('ix_file_asset_logical_path'), 'file_asset', ['logical_path'], unique=False)
    op.create_index(op.f('ix_file_asset_object_id'), 'file_asset', ['object_id'], unique=False)
    op.create_index('ix_file_asset_team_domain_obj', 'file_asset', ['team_id', 'domain', 'object_id'], unique=False)
    op.create_index(op.f('ix_file_asset_team_id'), 'file_asset', ['team_id'], unique=False)
    op.create_index('ix_file_asset_team_id_id', 'file_asset', ['team_id', 'id'], unique=False)
    op.create_table('permission_groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('system_key', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('excluded_attribute_ids', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'id', name='uq_permission_groups_team_id_id'),
    sa.UniqueConstraint('team_id', 'system_key', name='uq_permgroup_system_key')
    )
    op.create_index(op.f('ix_permission_groups_team_id'), 'permission_groups', ['team_id'], unique=False)
    op.create_index('ix_permission_groups_team_id_id', 'permission_groups', ['team_id', 'id'], unique=False)
    op.create_table('permission_group_permissions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id', 'group_id'], ['permission_groups.team_id', 'permission_groups.id'], name='fk_pgperm_group_team_id_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'group_id', 'permission_id', name='uq_pgperm_team_group_perm'),
    sa.UniqueConstraint('team_id', 'id', name='uq_pgperm_team_id_id')
    )
    op.create_index(op.f('ix_permission_group_permissions_group_id'), 'permission_group_permissions', ['group_id'], unique=False)
    op.create_index(op.f('ix_permission_group_permissions_permission_id'), 'permission_group_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_permission_group_permissions_team_id'), 'permission_group_permissions', ['team_id'], unique=False)
    op.create_index('ix_pgperm_team_group', 'permission_group_permissions', ['team_id', 'group_id'], unique=False)
    op.create_index('ix_pgperm_team_permission', 'permission_group_permissions', ['team_id', 'permission_id'], unique=False)
    op.create_table('user_teams',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('permission_group_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['permission_group_id'], ['permission_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_user_team')
    )
    op.create_index('ix_user_teams_permission_group_id', 'user_teams', ['permission_group_id'], unique=False)
    op.create_index('ix_user_teams_team_id', 'user_teams', ['team_id'], unique=False)
    op.create_index('ix_user_teams_user_id', 'user_teams', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_teams_user_id', table_name='user_teams')
    op.drop_index('ix_user_teams_team_id', table_name='user_teams')
    op.drop_index('ix_user_teams_permission_group_id', table_name='user_teams')
    op.drop_table('user_teams')
    op.drop_index('ix_pgperm_team_permission', table_name='permission_group_permissions')
    op.drop_index('ix_pgperm_team_group', table_name='permission_group_permissions')
    op.drop_index(op.f('ix_permission_group_permissions_team_id'), table_name='permission_group_permissions')
    op.drop_index(op.f('ix_permission_group_permissions_permission_id'), table_name='permission_group_permissions')
    op.drop_index(op.f('ix_permission_group_permissions_group_id'), table_name='permission_group_permissions')
    op.drop_table('permission_group_permissions')
    op.drop_index('ix_permission_groups_team_id_id', table_name='permission_groups')
    op.drop_index(op.f('ix_permission_groups_team_id'), table_name='permission_groups')
    op.drop_table('permission_groups')
    op.drop_index('ix_file_asset_team_id_id', table_name='file_asset')
    op.drop_index(op.f('ix_file_asset_team_id'), table_name='file_asset')
    op.drop_index('ix_file_asset_team_domain_obj', table_name='file_asset')
    op.drop_index(op.f('ix_file_asset_object_id'), table_name='file_asset')
    op.drop_index(op.f('ix_file_asset_logical_path'), table_name='file_asset')
    op.drop_index('ix_file_asset_domain_obj', table_name='file_asset')
    op.drop_table('file_asset')
    op.drop_index(op.f('ix_teams_purge_at'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_index('ix_permissions_category', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('uq_user_oauth_active', table_name='user')
    op.drop_index('uq_user_email_active_true', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_auth_provider', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
