"""phase_b_master_data

Revision ID: 4e203604f2d9
Revises: 00b864b4edec
Create Date: 2026-04-26 11:02:33.414296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e203604f2d9'
down_revision: Union[str, None] = '00b864b4edec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('billing_address', sa.String(length=500), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_customer_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_customer_tenant_id_id')
    )
    op.create_index('ix_customer_tenant_active_id', 'customer', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index(op.f('ix_customer_tenant_id'), 'customer', ['tenant_id'], unique=False)
    op.create_index('ix_customer_tenant_name', 'customer', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_customer_tenant_updated_at', 'customer', ['tenant_id', 'updated_at'], unique=False)
    op.create_table('driver',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('license_state', sa.String(length=8), nullable=True),
    sa.Column('truck_number', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_driver_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'truck_number', name='uq_driver_tenant_truck'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_driver_tenant_user')
    )
    op.create_index('ix_driver_tenant_active_id', 'driver', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index(op.f('ix_driver_tenant_id'), 'driver', ['tenant_id'], unique=False)
    op.create_index('ix_driver_tenant_updated_at', 'driver', ['tenant_id', 'updated_at'], unique=False)
    op.create_index('ix_driver_tenant_user', 'driver', ['tenant_id', 'user_id'], unique=False)
    op.create_table('terminal',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_terminal_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_terminal_tenant_id_id')
    )
    op.create_index('ix_terminal_tenant_active_id', 'terminal', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index(op.f('ix_terminal_tenant_id'), 'terminal', ['tenant_id'], unique=False)
    op.create_index('ix_terminal_tenant_name', 'terminal', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_terminal_tenant_updated_at', 'terminal', ['tenant_id', 'updated_at'], unique=False)
    op.create_table('vessel',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('imo_number', sa.String(length=16), nullable=True),
    sa.Column('line', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_vessel_tenant_id_id'),
    sa.UniqueConstraint('tenant_id', 'imo_number', name='uq_vessel_tenant_imo')
    )
    op.create_index('ix_vessel_tenant_active_id', 'vessel', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index(op.f('ix_vessel_tenant_id'), 'vessel', ['tenant_id'], unique=False)
    op.create_index('ix_vessel_tenant_name', 'vessel', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_vessel_tenant_updated_at', 'vessel', ['tenant_id', 'updated_at'], unique=False)
    op.create_table('location',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('YARD', 'CUSTOMER', 'PORT', 'OTHER', name='location_kind'), server_default='YARD', nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_location_tenant_id_id')
    )
    op.create_index('ix_location_tenant_active_id', 'location', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_location_tenant_customer', 'location', ['tenant_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_location_tenant_id'), 'location', ['tenant_id'], unique=False)
    op.create_index('ix_location_tenant_kind', 'location', ['tenant_id', 'kind'], unique=False)
    op.create_index('ix_location_tenant_name', 'location', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_location_tenant_updated_at', 'location', ['tenant_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_tenant_updated_at', table_name='location')
    op.drop_index('ix_location_tenant_name', table_name='location')
    op.drop_index('ix_location_tenant_kind', table_name='location')
    op.drop_index(op.f('ix_location_tenant_id'), table_name='location')
    op.drop_index('ix_location_tenant_customer', table_name='location')
    op.drop_index('ix_location_tenant_active_id', table_name='location')
    op.drop_table('location')
    op.drop_index('ix_vessel_tenant_updated_at', table_name='vessel')
    op.drop_index('ix_vessel_tenant_name', table_name='vessel')
    op.drop_index(op.f('ix_vessel_tenant_id'), table_name='vessel')
    op.drop_index('ix_vessel_tenant_active_id', table_name='vessel')
    op.drop_table('vessel')
    op.drop_index('ix_terminal_tenant_updated_at', table_name='terminal')
    op.drop_index('ix_terminal_tenant_name', table_name='terminal')
    op.drop_index(op.f('ix_terminal_tenant_id'), table_name='terminal')
    op.drop_index('ix_terminal_tenant_active_id', table_name='terminal')
    op.drop_table('terminal')
    op.drop_index('ix_driver_tenant_user', table_name='driver')
    op.drop_index('ix_driver_tenant_updated_at', table_name='driver')
    op.drop_index(op.f('ix_driver_tenant_id'), table_name='driver')
    op.drop_index('ix_driver_tenant_active_id', table_name='driver')
    op.drop_table('driver')
    op.drop_index('ix_customer_tenant_updated_at', table_name='customer')
    op.drop_index('ix_customer_tenant_name', table_name='customer')
    op.drop_index(op.f('ix_customer_tenant_id'), table_name='customer')
    op.drop_index('ix_customer_tenant_active_id', table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
