"""expand containers size_type to varchar 50

Revision ID: 594a98baa02e
Revises: b2c3d4e5f6g7
Create Date: 2026-04-08 09:53:42.085077
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '594a98baa02e'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('containers', 'size_type',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('containers', 'size_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
