"""phase_c_do_leg_settlement

Revision ID: 66e45de2765c
Revises: 4e203604f2d9
Create Date: 2026-04-26 11:16:03.014844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e45de2765c'
down_revision: Union[str, None] = '4e203604f2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    NOTE: 자동 생성된 op.create_table 순서가 FK 의존성을 위반한다 (alembic 의
    sorted_tables 가 일부 케이스에서 잘못 정렬). FK_CHECKS 를 일시 끄고 모든
    테이블을 만든 후 재활성화한다 — MySQL 전용.
    """
    op.execute("SET FOREIGN_KEY_CHECKS=0")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leg',
    sa.Column('delivery_order_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Enum('PLANNING', 'DISPATCHED', 'YARD_STAGED', 'FINAL_DELIVERY', 'EMPTY_STAGED', 'COMPLETED', name='delivery_status'), nullable=False),
    sa.Column('move_type', sa.Enum('LOADED', 'EMPTY', name='move_type'), nullable=False),
    sa.Column('service_type', sa.Enum('LIVE', 'DROP', name='service_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'COMPLETED', 'FAILED', name='leg_status'), server_default='PENDING', nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('pickup_location_id', sa.Integer(), nullable=True),
    sa.Column('pickup_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_location_id', sa.Integer(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('storage_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_settled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delivery_order_id'], ['delivery_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_leg_tenant_id_id')
    )
    op.create_index('ix_leg_tenant_active_id', 'leg', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_leg_tenant_do', 'leg', ['tenant_id', 'delivery_order_id'], unique=False)
    op.create_index('ix_leg_tenant_driver', 'leg', ['tenant_id', 'driver_id'], unique=False)
    op.create_index(op.f('ix_leg_tenant_id'), 'leg', ['tenant_id'], unique=False)
    op.create_index('ix_leg_tenant_pickup', 'leg', ['tenant_id', 'pickup_date'], unique=False)
    op.create_index('ix_leg_tenant_status', 'leg', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_leg_tenant_updated_at', 'leg', ['tenant_id', 'updated_at'], unique=False)
    op.create_table('settlement',
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('settlement_status', sa.Enum('PENDING', 'CALCULATED', 'ADJUSTED', 'APPROVED', name='settlement_status'), server_default='PENDING', nullable=False),
    sa.Column('system_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('driver_reported_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discrepancy', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('has_flag', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_settled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('unapproved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unapproved_by', sa.Integer(), nullable=True),
    sa.Column('unapproved_reason', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leg_id'], ['leg.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unapproved_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leg_id', name='uq_settlement_leg_unique'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_settlement_tenant_id_id')
    )
    op.create_index('ix_settlement_tenant_active_id', 'settlement', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_settlement_tenant_has_flag', 'settlement', ['tenant_id', 'has_flag'], unique=False)
    op.create_index(op.f('ix_settlement_tenant_id'), 'settlement', ['tenant_id'], unique=False)
    op.create_index('ix_settlement_tenant_status', 'settlement', ['tenant_id', 'settlement_status'], unique=False)
    op.create_index('ix_settlement_tenant_updated_at', 'settlement', ['tenant_id', 'updated_at'], unique=False)
    op.create_table('extra_charge',
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_extra_charge_tenant_id_id')
    )
    op.create_index('ix_extra_charge_tenant_active_id', 'extra_charge', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index(op.f('ix_extra_charge_tenant_id'), 'extra_charge', ['tenant_id'], unique=False)
    op.create_index('ix_extra_charge_tenant_settlement', 'extra_charge', ['tenant_id', 'settlement_id'], unique=False)
    op.create_index('ix_extra_charge_tenant_type', 'extra_charge', ['tenant_id', 'type'], unique=False)
    op.create_table('rate_setting',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rate_type', sa.Enum('FLAT_RATE', 'PERCENTAGE', 'PER_MILE', name='rate_type'), nullable=False),
    sa.Column('flat_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rate_percent', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('rate_per_mile', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_rate_setting_tenant_id_id')
    )
    op.create_index('ix_rate_setting_tenant_active_id', 'rate_setting', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_rate_setting_tenant_effective', 'rate_setting', ['tenant_id', 'effective_date'], unique=False)
    op.create_index(op.f('ix_rate_setting_tenant_id'), 'rate_setting', ['tenant_id'], unique=False)
    op.create_index('ix_rate_setting_tenant_name', 'rate_setting', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_rate_setting_tenant_updated_at', 'rate_setting', ['tenant_id', 'updated_at'], unique=False)
    op.create_table('settlement_audit_log',
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CALCULATE', 'ADJUST', 'APPROVE', 'UNAPPROVE', name='settlement_audit_action'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_settlement_audit_tenant_id_id')
    )
    op.create_index(op.f('ix_settlement_audit_log_tenant_id'), 'settlement_audit_log', ['tenant_id'], unique=False)
    op.create_index('ix_settlement_audit_tenant_action', 'settlement_audit_log', ['tenant_id', 'action'], unique=False)
    op.create_index('ix_settlement_audit_tenant_active_id', 'settlement_audit_log', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_settlement_audit_tenant_created_at', 'settlement_audit_log', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_settlement_audit_tenant_settlement', 'settlement_audit_log', ['tenant_id', 'settlement_id'], unique=False)
    op.create_table('delivery_order',
    sa.Column('status', sa.Enum('PLANNING', 'DISPATCHED', 'YARD_STAGED', 'FINAL_DELIVERY', 'EMPTY_STAGED', 'COMPLETED', name='delivery_status'), server_default='PLANNING', nullable=False),
    sa.Column('direction', sa.Enum('IMPORT', 'EXPORT', name='shipment_direction'), nullable=False),
    sa.Column('bl_number', sa.String(length=64), nullable=True),
    sa.Column('booking_number', sa.String(length=64), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.Column('delivery_location_id', sa.Integer(), nullable=True),
    sa.Column('return_location_id', sa.Integer(), nullable=True),
    sa.Column('container_number', sa.String(length=11), nullable=True),
    sa.Column('container_size', sa.Enum('SIZE_20GP', 'SIZE_40GP', 'SIZE_40HC', 'SIZE_40OT', 'SIZE_45HC', 'SIZE_20RF', 'SIZE_40RF', name='container_size'), nullable=True),
    sa.Column('container_type', sa.String(length=32), nullable=True),
    sa.Column('chassis_number', sa.String(length=32), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_appointment', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_appointment', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_appointment', sa.DateTime(timezone=True), nullable=True),
    sa.Column('demurrage_lfd', sa.Date(), nullable=True),
    sa.Column('detention_lfd', sa.Date(), nullable=True),
    sa.Column('empty_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loaded_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bl_released', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('pier_pass_paid', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('customs_cleared', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['return_location_id'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessel.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_delivery_order_tenant_id_id')
    )
    op.create_index(op.f('ix_delivery_order_tenant_id'), 'delivery_order', ['tenant_id'], unique=False)
    op.create_index('ix_do_tenant_active_id', 'delivery_order', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_do_tenant_container', 'delivery_order', ['tenant_id', 'container_number'], unique=False)
    op.create_index('ix_do_tenant_customer', 'delivery_order', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_do_tenant_demurrage_lfd', 'delivery_order', ['tenant_id', 'demurrage_lfd'], unique=False)
    op.create_index('ix_do_tenant_detention_lfd', 'delivery_order', ['tenant_id', 'detention_lfd'], unique=False)
    op.create_index('ix_do_tenant_direction', 'delivery_order', ['tenant_id', 'direction'], unique=False)
    op.create_index('ix_do_tenant_status', 'delivery_order', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_do_tenant_updated_at', 'delivery_order', ['tenant_id', 'updated_at'], unique=False)
    op.create_table('street_turn',
    sa.Column('import_order_id', sa.Integer(), nullable=False),
    sa.Column('export_order_id', sa.Integer(), nullable=False),
    sa.Column('container_number', sa.String(length=11), nullable=False),
    sa.Column('link_type', sa.Enum('AUTO', 'MANUAL', name='street_turn_link_type'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['export_order_id'], ['delivery_order.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_order_id'], ['delivery_order.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('export_order_id', name='uq_street_turn_export'),
    sa.UniqueConstraint('import_order_id', name='uq_street_turn_import'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_street_turn_tenant_id_id')
    )
    op.create_index('ix_street_turn_tenant_active_id', 'street_turn', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_street_turn_tenant_container', 'street_turn', ['tenant_id', 'container_number'], unique=False)
    op.create_index(op.f('ix_street_turn_tenant_id'), 'street_turn', ['tenant_id'], unique=False)
    op.create_index('ix_street_turn_tenant_updated_at', 'street_turn', ['tenant_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###
    op.execute("SET FOREIGN_KEY_CHECKS=1")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_street_turn_tenant_updated_at', table_name='street_turn')
    op.drop_index(op.f('ix_street_turn_tenant_id'), table_name='street_turn')
    op.drop_index('ix_street_turn_tenant_container', table_name='street_turn')
    op.drop_index('ix_street_turn_tenant_active_id', table_name='street_turn')
    op.drop_table('street_turn')
    op.drop_index('ix_do_tenant_updated_at', table_name='delivery_order')
    op.drop_index('ix_do_tenant_status', table_name='delivery_order')
    op.drop_index('ix_do_tenant_direction', table_name='delivery_order')
    op.drop_index('ix_do_tenant_detention_lfd', table_name='delivery_order')
    op.drop_index('ix_do_tenant_demurrage_lfd', table_name='delivery_order')
    op.drop_index('ix_do_tenant_customer', table_name='delivery_order')
    op.drop_index('ix_do_tenant_container', table_name='delivery_order')
    op.drop_index('ix_do_tenant_active_id', table_name='delivery_order')
    op.drop_index(op.f('ix_delivery_order_tenant_id'), table_name='delivery_order')
    op.drop_table('delivery_order')
    op.drop_index('ix_settlement_audit_tenant_settlement', table_name='settlement_audit_log')
    op.drop_index('ix_settlement_audit_tenant_created_at', table_name='settlement_audit_log')
    op.drop_index('ix_settlement_audit_tenant_active_id', table_name='settlement_audit_log')
    op.drop_index('ix_settlement_audit_tenant_action', table_name='settlement_audit_log')
    op.drop_index(op.f('ix_settlement_audit_log_tenant_id'), table_name='settlement_audit_log')
    op.drop_table('settlement_audit_log')
    op.drop_index('ix_rate_setting_tenant_updated_at', table_name='rate_setting')
    op.drop_index('ix_rate_setting_tenant_name', table_name='rate_setting')
    op.drop_index(op.f('ix_rate_setting_tenant_id'), table_name='rate_setting')
    op.drop_index('ix_rate_setting_tenant_effective', table_name='rate_setting')
    op.drop_index('ix_rate_setting_tenant_active_id', table_name='rate_setting')
    op.drop_table('rate_setting')
    op.drop_index('ix_extra_charge_tenant_type', table_name='extra_charge')
    op.drop_index('ix_extra_charge_tenant_settlement', table_name='extra_charge')
    op.drop_index(op.f('ix_extra_charge_tenant_id'), table_name='extra_charge')
    op.drop_index('ix_extra_charge_tenant_active_id', table_name='extra_charge')
    op.drop_table('extra_charge')
    op.drop_index('ix_settlement_tenant_updated_at', table_name='settlement')
    op.drop_index('ix_settlement_tenant_status', table_name='settlement')
    op.drop_index(op.f('ix_settlement_tenant_id'), table_name='settlement')
    op.drop_index('ix_settlement_tenant_has_flag', table_name='settlement')
    op.drop_index('ix_settlement_tenant_active_id', table_name='settlement')
    op.drop_table('settlement')
    op.drop_index('ix_leg_tenant_updated_at', table_name='leg')
    op.drop_index('ix_leg_tenant_status', table_name='leg')
    op.drop_index('ix_leg_tenant_pickup', table_name='leg')
    op.drop_index(op.f('ix_leg_tenant_id'), table_name='leg')
    op.drop_index('ix_leg_tenant_driver', table_name='leg')
    op.drop_index('ix_leg_tenant_do', table_name='leg')
    op.drop_index('ix_leg_tenant_active_id', table_name='leg')
    op.drop_table('leg')
    # ### end Alembic commands ###
