"""master expiry fields (truck/chassis/driver DQ)

Revision ID: 8d1652ee0927
Revises: 0b60ce5bffa7
Create Date: 2026-06-09 18:53:51.755998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1652ee0927'
down_revision: Union[str, None] = '0b60ce5bffa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chassis', sa.Column('registration_expires_at', sa.Date(), nullable=True))
    op.add_column('chassis', sa.Column('inspection_expires_at', sa.Date(), nullable=True))
    op.add_column('driver', sa.Column('twic_expires_at', sa.Date(), nullable=True))
    op.add_column('driver', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('truck', sa.Column('registration_expires_at', sa.Date(), nullable=True))
    op.add_column('truck', sa.Column('insurance_expires_at', sa.Date(), nullable=True))
    op.add_column('truck', sa.Column('inspection_expires_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('truck', 'inspection_expires_at')
    op.drop_column('truck', 'insurance_expires_at')
    op.drop_column('truck', 'registration_expires_at')
    op.drop_column('driver', 'hire_date')
    op.drop_column('driver', 'twic_expires_at')
    op.drop_column('chassis', 'inspection_expires_at')
    op.drop_column('chassis', 'registration_expires_at')
    # ### end Alembic commands ###
