"""delivery_order hold/cancel overlay (phase6)

Revision ID: 969c61fa6a08
Revises: 3442834d82d5
Create Date: 2026-06-09 19:08:04.997900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969c61fa6a08'
down_revision: Union[str, None] = '3442834d82d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_order', sa.Column('is_on_hold', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('delivery_order', sa.Column('hold_reason', sa.String(length=500), nullable=True))
    op.add_column('delivery_order', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_order', sa.Column('cancel_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_order', 'cancel_reason')
    op.drop_column('delivery_order', 'cancelled_at')
    op.drop_column('delivery_order', 'hold_reason')
    op.drop_column('delivery_order', 'is_on_hold')
    # ### end Alembic commands ###
