"""add api_key domain

Revision ID: 9a548df867f5
Revises: 1882a14b7386
Create Date: 2026-04-27 11:11:35.599435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a548df867f5'
down_revision: Union[str, None] = '1882a14b7386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_api_key_key'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_api_key_tenant_id_id')
    )
    op.create_index('ix_api_key_prefix', 'api_key', ['prefix'], unique=False)
    op.create_index('ix_api_key_tenant_active_id', 'api_key', ['tenant_id', 'is_active', 'id'], unique=False)
    op.create_index(op.f('ix_api_key_tenant_id'), 'api_key', ['tenant_id'], unique=False)
    op.create_index('ix_api_key_tenant_prefix', 'api_key', ['tenant_id', 'prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_key_tenant_prefix', table_name='api_key')
    op.drop_index(op.f('ix_api_key_tenant_id'), table_name='api_key')
    op.drop_index('ix_api_key_tenant_active_id', table_name='api_key')
    op.drop_index('ix_api_key_prefix', table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
