"""add payroll

Revision ID: a99a4355b7e6
Revises: f56691bd0ca7
Create Date: 2026-06-09 17:44:53.062794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99a4355b7e6'
down_revision: Union[str, None] = 'f56691bd0ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_settlement',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PAID', 'VOID', name='payroll_status'), server_default='DRAFT', nullable=False),
    sa.Column('base_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('accessorial_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'id', name='uq_payroll_settlement_team_id_id')
    )
    op.create_index('ix_payroll_settlement_team_active_id', 'payroll_settlement', ['team_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_payroll_settlement_team_driver', 'payroll_settlement', ['team_id', 'driver_id'], unique=False)
    op.create_index(op.f('ix_payroll_settlement_team_id'), 'payroll_settlement', ['team_id'], unique=False)
    op.create_index('ix_payroll_settlement_team_period', 'payroll_settlement', ['team_id', 'period_start', 'period_end'], unique=False)
    op.create_index('ix_payroll_settlement_team_status', 'payroll_settlement', ['team_id', 'status'], unique=False)
    op.create_index('ix_payroll_settlement_team_updated_at', 'payroll_settlement', ['team_id', 'updated_at'], unique=False)
    op.create_table('payroll_charge',
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('accessorial_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('snapshot_unit_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), server_default='1', nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessorial_id'], ['accessorial.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id', 'settlement_id'], ['payroll_settlement.team_id', 'payroll_settlement.id'], name='fk_payroll_charge_settlement_team_id_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'id', name='uq_payroll_charge_team_id_id')
    )
    op.create_index(op.f('ix_payroll_charge_team_id'), 'payroll_charge', ['team_id'], unique=False)
    op.create_index('ix_payroll_charge_team_id_id', 'payroll_charge', ['team_id', 'id'], unique=False)
    op.create_index('ix_payroll_charge_team_settlement', 'payroll_charge', ['team_id', 'settlement_id'], unique=False)
    op.create_table('payroll_line',
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('leg_id', sa.Integer(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('source', sa.Enum('RESOLVED', 'UNRESOLVED', 'MANUAL', name='payroll_line_source'), server_default='RESOLVED', nullable=False),
    sa.Column('rate_snapshot', sa.JSON(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leg_id'], ['leg.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id', 'settlement_id'], ['payroll_settlement.team_id', 'payroll_settlement.id'], name='fk_payroll_line_settlement_team_id_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'id', name='uq_payroll_line_team_id_id')
    )
    op.create_index(op.f('ix_payroll_line_team_id'), 'payroll_line', ['team_id'], unique=False)
    op.create_index('ix_payroll_line_team_id_id', 'payroll_line', ['team_id', 'id'], unique=False)
    op.create_index('ix_payroll_line_team_leg', 'payroll_line', ['team_id', 'leg_id'], unique=False)
    op.create_index('ix_payroll_line_team_settlement', 'payroll_line', ['team_id', 'settlement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payroll_line_team_settlement', table_name='payroll_line')
    op.drop_index('ix_payroll_line_team_leg', table_name='payroll_line')
    op.drop_index('ix_payroll_line_team_id_id', table_name='payroll_line')
    op.drop_index(op.f('ix_payroll_line_team_id'), table_name='payroll_line')
    op.drop_table('payroll_line')
    op.drop_index('ix_payroll_charge_team_settlement', table_name='payroll_charge')
    op.drop_index('ix_payroll_charge_team_id_id', table_name='payroll_charge')
    op.drop_index(op.f('ix_payroll_charge_team_id'), table_name='payroll_charge')
    op.drop_table('payroll_charge')
    op.drop_index('ix_payroll_settlement_team_updated_at', table_name='payroll_settlement')
    op.drop_index('ix_payroll_settlement_team_status', table_name='payroll_settlement')
    op.drop_index('ix_payroll_settlement_team_period', table_name='payroll_settlement')
    op.drop_index(op.f('ix_payroll_settlement_team_id'), table_name='payroll_settlement')
    op.drop_index('ix_payroll_settlement_team_driver', table_name='payroll_settlement')
    op.drop_index('ix_payroll_settlement_team_active_id', table_name='payroll_settlement')
    op.drop_table('payroll_settlement')
    # ### end Alembic commands ###
