"""sync schema drift baseline

Revision ID: cc7cd522d91a
Revises: 101f7a2e6abf
Create Date: 2026-06-09 17:09:45.489861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc7cd522d91a'
down_revision: Union[str, None] = '101f7a2e6abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_container_stop_team_id'), 'container_stop', ['team_id'], unique=False)
    op.drop_index('ix_do_team_container', table_name='delivery_order')
    op.drop_index('ix_do_team_demurrage_lfd', table_name='delivery_order')
    op.drop_index('ix_do_team_detention_lfd', table_name='delivery_order')
    op.create_foreign_key('fk_delivery_order_customer_id', 'delivery_order', 'customer', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_distance_matrix_team_id'), 'distance_matrix', ['team_id'], unique=False)
    op.drop_index('ix_leg_charge_team_payee_driver', table_name='leg_charge')
    op.drop_index('ix_leg_charge_team_payee_partner', table_name='leg_charge')
    op.create_index(op.f('ix_leg_driver_segment_team_id'), 'leg_driver_segment', ['team_id'], unique=False)
    op.create_index(op.f('ix_leg_rate_team_id'), 'leg_rate', ['team_id'], unique=False)
    op.create_index(op.f('ix_rate_multiplier_team_id'), 'rate_multiplier', ['team_id'], unique=False)
    op.alter_column('rate_quote', 'container_size',
               existing_type=mysql.ENUM('20GP', '40GP', '40HC', '40OT', '45HC', '20RF', '40RF'),
               type_=sa.Enum('SIZE_20GP', 'SIZE_40GP', 'SIZE_40HC', 'SIZE_40OT', 'SIZE_45HC', 'SIZE_20RF', 'SIZE_40RF', name='container_size'),
               existing_nullable=True)
    op.create_index(op.f('ix_rate_quote_team_id'), 'rate_quote', ['team_id'], unique=False)
    op.alter_column('rate_tariff', 'container_size',
               existing_type=mysql.ENUM('20GP', '40GP', '40HC', '40OT', '45HC', '20RF', '40RF'),
               type_=sa.Enum('SIZE_20GP', 'SIZE_40GP', 'SIZE_40HC', 'SIZE_40OT', 'SIZE_45HC', 'SIZE_20RF', 'SIZE_40RF', name='container_size'),
               existing_nullable=True)
    op.create_index(op.f('ix_rate_tariff_team_id'), 'rate_tariff', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_tariff_team_id'), table_name='rate_tariff')
    op.alter_column('rate_tariff', 'container_size',
               existing_type=sa.Enum('SIZE_20GP', 'SIZE_40GP', 'SIZE_40HC', 'SIZE_40OT', 'SIZE_45HC', 'SIZE_20RF', 'SIZE_40RF', name='container_size'),
               type_=mysql.ENUM('20GP', '40GP', '40HC', '40OT', '45HC', '20RF', '40RF'),
               existing_nullable=True)
    op.drop_index(op.f('ix_rate_quote_team_id'), table_name='rate_quote')
    op.alter_column('rate_quote', 'container_size',
               existing_type=sa.Enum('SIZE_20GP', 'SIZE_40GP', 'SIZE_40HC', 'SIZE_40OT', 'SIZE_45HC', 'SIZE_20RF', 'SIZE_40RF', name='container_size'),
               type_=mysql.ENUM('20GP', '40GP', '40HC', '40OT', '45HC', '20RF', '40RF'),
               existing_nullable=True)
    op.drop_index(op.f('ix_rate_multiplier_team_id'), table_name='rate_multiplier')
    op.drop_index(op.f('ix_leg_rate_team_id'), table_name='leg_rate')
    op.drop_index(op.f('ix_leg_driver_segment_team_id'), table_name='leg_driver_segment')
    op.create_index('ix_leg_charge_team_payee_partner', 'leg_charge', ['team_id', 'payee_partner_id'], unique=False)
    op.create_index('ix_leg_charge_team_payee_driver', 'leg_charge', ['team_id', 'payee_driver_id'], unique=False)
    op.drop_index(op.f('ix_distance_matrix_team_id'), table_name='distance_matrix')
    op.drop_constraint('fk_delivery_order_customer_id', 'delivery_order', type_='foreignkey')
    op.create_index('ix_do_team_detention_lfd', 'delivery_order', ['team_id'], unique=False)
    op.create_index('ix_do_team_demurrage_lfd', 'delivery_order', ['team_id'], unique=False)
    op.create_index('ix_do_team_container', 'delivery_order', ['team_id'], unique=False)
    op.drop_index(op.f('ix_container_stop_team_id'), table_name='container_stop')
    # ### end Alembic commands ###
