"""add leg_layer

Revision ID: db7a5c780ae8
Revises: cc7cd522d91a
Create Date: 2026-06-09 17:14:52.352753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7a5c780ae8'
down_revision: Union[str, None] = 'cc7cd522d91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leg_addon',
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Enum('CHS', 'HZM', 'OOG', 'RFR', 'CXM', 'LYO', 'RSP', 'FLT', 'TNK', 'NGT', 'WKD', 'EGT', 'LFT', 'PPS', name='leg_addon_code'), nullable=False),
    sa.Column('amount_override', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id', 'leg_id'], ['leg.team_id', 'leg.id'], name='fk_leg_addon_leg_team_id_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'id', name='uq_leg_addon_team_id_id'),
    sa.UniqueConstraint('team_id', 'leg_id', 'code', name='uq_leg_addon_leg_code')
    )
    op.create_index(op.f('ix_leg_addon_team_id'), 'leg_addon', ['team_id'], unique=False)
    op.create_index('ix_leg_addon_team_id_id', 'leg_addon', ['team_id', 'id'], unique=False)
    op.create_index('ix_leg_addon_team_leg', 'leg_addon', ['team_id', 'leg_id'], unique=False)
    op.create_table('leg_charge_event',
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Enum('DET', 'DMR', 'YRD', 'STP', name='leg_charge_event_code'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('free_minutes', sa.Integer(), nullable=True),
    sa.Column('free_days', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_days', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id', 'leg_id'], ['leg.team_id', 'leg.id'], name='fk_leg_charge_event_leg_team_id_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'id', name='uq_leg_charge_event_team_id_id'),
    sa.UniqueConstraint('team_id', 'leg_id', 'code', name='uq_leg_charge_event_leg_code')
    )
    op.create_index(op.f('ix_leg_charge_event_team_id'), 'leg_charge_event', ['team_id'], unique=False)
    op.create_index('ix_leg_charge_event_team_id_id', 'leg_charge_event', ['team_id', 'id'], unique=False)
    op.create_index('ix_leg_charge_event_team_leg', 'leg_charge_event', ['team_id', 'leg_id'], unique=False)
    op.create_table('leg_stop_off',
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('pod_file_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pod_file_id'], ['file_asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id', 'leg_id'], ['leg.team_id', 'leg.id'], name='fk_leg_stop_off_leg_team_id_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'id', name='uq_leg_stop_off_team_id_id')
    )
    op.create_index(op.f('ix_leg_stop_off_team_id'), 'leg_stop_off', ['team_id'], unique=False)
    op.create_index('ix_leg_stop_off_team_id_id', 'leg_stop_off', ['team_id', 'id'], unique=False)
    op.create_index('ix_leg_stop_off_team_leg', 'leg_stop_off', ['team_id', 'leg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leg_stop_off_team_leg', table_name='leg_stop_off')
    op.drop_index('ix_leg_stop_off_team_id_id', table_name='leg_stop_off')
    op.drop_index(op.f('ix_leg_stop_off_team_id'), table_name='leg_stop_off')
    op.drop_table('leg_stop_off')
    op.drop_index('ix_leg_charge_event_team_leg', table_name='leg_charge_event')
    op.drop_index('ix_leg_charge_event_team_id_id', table_name='leg_charge_event')
    op.drop_index(op.f('ix_leg_charge_event_team_id'), table_name='leg_charge_event')
    op.drop_table('leg_charge_event')
    op.drop_index('ix_leg_addon_team_leg', table_name='leg_addon')
    op.drop_index('ix_leg_addon_team_id_id', table_name='leg_addon')
    op.drop_index(op.f('ix_leg_addon_team_id'), table_name='leg_addon')
    op.drop_table('leg_addon')
    # ### end Alembic commands ###
