"""add invoice + invoice_line (2c)

Revision ID: dfc5c2c9009e
Revises: a99a4355b7e6
Create Date: 2026-06-09 18:26:28.576799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dfc5c2c9009e'
down_revision: Union[str, None] = 'a99a4355b7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('delivery_order_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'VOID', name='invoice_status'), server_default='DRAFT', nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('cost_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('charge_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delivery_order_id'], ['delivery_order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'id', name='uq_invoice_team_id_id')
    )
    op.create_index('ix_invoice_team_active_id', 'invoice', ['team_id', 'is_active', 'id'], unique=False)
    op.create_index('ix_invoice_team_customer', 'invoice', ['team_id', 'customer_id'], unique=False)
    op.create_index('ix_invoice_team_do', 'invoice', ['team_id', 'delivery_order_id'], unique=False)
    op.create_index(op.f('ix_invoice_team_id'), 'invoice', ['team_id'], unique=False)
    op.create_index('ix_invoice_team_status', 'invoice', ['team_id', 'status'], unique=False)
    op.create_index('ix_invoice_team_updated_at', 'invoice', ['team_id', 'updated_at'], unique=False)
    op.create_table('invoice_line',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), server_default='1', nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('source', sa.Enum('PREFILL', 'MANUAL', name='invoice_line_source'), server_default='MANUAL', nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id', 'invoice_id'], ['invoice.team_id', 'invoice.id'], name='fk_invoice_line_invoice_team_id_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'id', name='uq_invoice_line_team_id_id')
    )
    op.create_index(op.f('ix_invoice_line_team_id'), 'invoice_line', ['team_id'], unique=False)
    op.create_index('ix_invoice_line_team_id_id', 'invoice_line', ['team_id', 'id'], unique=False)
    op.create_index('ix_invoice_line_team_invoice', 'invoice_line', ['team_id', 'invoice_id'], unique=False)
    # NOTE: rate_setting(구 v3) 테이블 drop 은 별도 Wave 1 정리에서 FK 해제와 함께 처리.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoice_line_team_invoice', table_name='invoice_line')
    op.drop_index('ix_invoice_line_team_id_id', table_name='invoice_line')
    op.drop_index(op.f('ix_invoice_line_team_id'), table_name='invoice_line')
    op.drop_table('invoice_line')
    op.drop_index('ix_invoice_team_updated_at', table_name='invoice')
    op.drop_index('ix_invoice_team_status', table_name='invoice')
    op.drop_index(op.f('ix_invoice_team_id'), table_name='invoice')
    op.drop_index('ix_invoice_team_do', table_name='invoice')
    op.drop_index('ix_invoice_team_customer', table_name='invoice')
    op.drop_index('ix_invoice_team_active_id', table_name='invoice')
    op.drop_table('invoice')
    # ### end Alembic commands ###
