"""leg reissued_from_leg_id (dry run)

Revision ID: e863e0648d25
Revises: 8d1652ee0927
Create Date: 2026-06-09 18:56:48.774887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e863e0648d25'
down_revision: Union[str, None] = '8d1652ee0927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leg', sa.Column('reissued_from_leg_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leg', 'reissued_from_leg_id')
    # ### end Alembic commands ###
