"""leg rate inputs

Revision ID: f56691bd0ca7
Revises: ae22b8f701e0
Create Date: 2026-06-09 17:40:30.386246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56691bd0ca7'
down_revision: Union[str, None] = 'ae22b8f701e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leg', sa.Column('rate_point_id', sa.Integer(), nullable=True))
    op.add_column('leg', sa.Column('dest_zip', sa.String(length=16), nullable=True))
    op.add_column('leg', sa.Column('dest_city', sa.String(length=120), nullable=True))
    op.add_column('leg', sa.Column('dest_state', sa.String(length=8), nullable=True))
    op.add_column('leg', sa.Column('rate_miles', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('leg', sa.Column('rate_hours', sa.Numeric(precision=8, scale=2), nullable=True))
    op.create_foreign_key(None, 'leg', 'rate_point', ['rate_point_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leg', type_='foreignkey')
    op.drop_column('leg', 'rate_hours')
    op.drop_column('leg', 'rate_miles')
    op.drop_column('leg', 'dest_state')
    op.drop_column('leg', 'dest_city')
    op.drop_column('leg', 'dest_zip')
    op.drop_column('leg', 'rate_point_id')
    # ### end Alembic commands ###
