"""영업권역(Service Area) 선언 테이블

확정 설계(컨플루언스 §8 방어 1): 팀이 영업 권역을 STATE/COUNTY/CITY/ZIP3 단위로
선언하면 요율 화면의 ZIP/도시 자동완성이 그 권역으로 좁혀진다.
입력 편의 필터 전용 — 해석/정산 경로와는 완전 무관.

- service_area: kind + state + value (STATE kind 는 value=state 동일값 —
  MySQL 유니크가 NULL 을 중복 허용해서 NULL 회피)
- uq(team, kind, state, value) + 소프트삭제 행 되살림(revive) 패턴으로 재선언 지원

Revision ID: rs16_service_area
Revises: rs15_zip_zone_layer
Create Date: 2026-06-11 22:59:47.807229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'rs16_service_area'
down_revision: Union[str, None] = 'rs15_zip_zone_layer'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_area',
    sa.Column('kind', sa.Enum('STATE', 'COUNTY', 'CITY', 'ZIP3', name='service_area_kind'), nullable=False),
    sa.Column('state', sa.String(length=8), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'id', name='uq_service_area_team_id_id'),
    sa.UniqueConstraint('team_id', 'kind', 'state', 'value', name='uq_service_area_selection')
    )
    op.create_index('ix_service_area_team_active_id', 'service_area', ['team_id', 'is_active', 'id'], unique=False)
    op.create_index(op.f('ix_service_area_team_id'), 'service_area', ['team_id'], unique=False)
    op.create_index('ix_service_area_team_updated_at', 'service_area', ['team_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_area_team_updated_at', table_name='service_area')
    op.drop_index(op.f('ix_service_area_team_id'), table_name='service_area')
    op.drop_index('ix_service_area_team_active_id', table_name='service_area')
    op.drop_table('service_area')
    # ### end Alembic commands ###
