"""존 종류(kind) — ZIP존/도시존 분리 강제

사용자 확정: 한 존에 zip 과 도시 혼합 금지. ZIP존(멤버=zip, 도시 추가는 확장 단축키),
도시존(멤버=도시, CITY 방식 전용). 해석도 kind 로 필터.
기존 데이터 보정: city 멤버를 가진 존은 CITY 로 승격(데이터 폐기 전제지만 보호용).

Revision ID: rs17_zone_kind
Revises: rs16_service_area
Create Date: 2026-06-12 10:20:27.982270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'rs17_zone_kind'
down_revision: Union[str, None] = 'rs16_service_area'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_zone', sa.Column('kind', sa.Enum('ZIP', 'CITY', name='zone_kind'), server_default='ZIP', nullable=False))
    # 기존 행 보정 — city 멤버 보유 존은 도시존
    op.execute(
        "UPDATE rate_zone z SET z.kind='CITY' WHERE EXISTS ("
        "SELECT 1 FROM rate_zone_member m WHERE m.zone_id = z.id AND m.city IS NOT NULL)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_zone', 'kind')
    # ### end Alembic commands ###
