# ===== Team Management =====
TEAM_RENAME = "TEAM_RENAME"
TEAM_DELETE = "TEAM_DELETE"
TEAM_MEMBER_INVITE = "TEAM_MEMBER_INVITE"
TEAM_MEMBER_REMOVE = "TEAM_MEMBER_REMOVE"
TEAM_MEMBER_ROLE_WRITE = "TEAM_MEMBER_ROLE_WRITE"
TEAM_MEMBER_PERMISSION_ASSIGN = "TEAM_MEMBER_PERMISSION_ASSIGN"

# Add your domain-specific permission codes here
# EXAMPLE_WRITE = "EXAMPLE_WRITE"
# EXAMPLE_READ = "EXAMPLE_READ"

def _unique(seq: list[str]) -> list[str]:
    seen = set()
    out: list[str] = []
    for x in seq:
        if x not in seen:
            out.append(x)
            seen.add(x)
    return out


ALL_PERMISSION_CODES = _unique([
    TEAM_RENAME, TEAM_DELETE,
    TEAM_MEMBER_INVITE, TEAM_MEMBER_REMOVE,
    TEAM_MEMBER_ROLE_WRITE, TEAM_MEMBER_PERMISSION_ASSIGN,
])

DEFAULT_ADMIN_CODES = ALL_PERMISSION_CODES[:]
DEFAULT_MEMBER_CODES = []
DEFAULT_VIEWER_CODES = []

GROUP_DEFAULTS_BY_SYSTEM_KEY = {
    "ADMIN": DEFAULT_ADMIN_CODES,
    "MEMBER": DEFAULT_MEMBER_CODES,
    "VIEWER": DEFAULT_VIEWER_CODES,
}
